### ISSUE TITLE
Options object are ignored

### ISSUE THREAD

**Issue by MilosMosovsky** [hard8candy/gulp-angular-translate-extractor#2]
Hello, i just investigated that in index.js you are parsing "options" from gulp but in file index.js on line

https://github.com/hard8candy/gulp-angular-translate-extractor/blob/master/index.js#L89

```
var _translation = new Translations({
        "safeMode": options.safeMode,
        "tree": false,
        "nullEmpty": false
      }, results),
```

You are overriding options, should not be 

```
var _translation = new Translations(otpions), results)
```

Or it is there on purpose ? Please let me know if i am correct , then i can make PR.

**Comment by ksenmal** [comment]
Hello,
sorry for a log delay with an answer!
'options' object contains not only Translations settings (safeMode, tree,...), but also some other options (startDelimiter, endDelimiter, dest,...). 
And I prefer this way (in the repository now):

```
var _translation = new Translations({
        "safeMode": options.safeMode,
        "tree": options.tree,
        "nullEmpty": options.nullEmpty
      }, results),
```

Thanks.
