### ISSUE TITLE
prefix and safeMode not working

### ISSUE THREAD

**Issue by elincognito** [hard8candy/gulp-angular-translate-extractor#7]
As the title says prefix isn't working for me.

My conf.paths.src i set to the 'src/app' folder i expected that the translation went to 'src/app/i18n' with the prefix 'resources-locale_' however they are being created in 'src/app' with no prefix
My gulp task:

```
"use strict";


var path = require('path');
var gulp = require('gulp');
var conf = require('./conf');
var extractTranslate = require('gulp-angular-translate-extractor'); 



 gulp.task('translate', function () {

  return gulp.src([
     path.join(conf.paths.src, '/**/*.js'),
     path.join(conf.paths.src, '/**/*.html')
 ])
 .pipe(extractTranslate({
     defaultLang: 'en-US',         // default language
    lang: ['pt'],   // array of languages
    prefix: 'resources-locale_',
    dest: 'i18n',             // destination
    safeMode: true,            // do not delete old translations, true - contrariwise
    stringifyOptions: true,     // force json to be sorted, false - contrariwise
 }))
 .pipe(gulp.dest(conf.paths.src));
});
```

**Comment by ksenmal** [comment]
Hello,
actually prefix option was not supported in this plugin.
But I've added prefix and suffix options. Starting from 1.0.2 version you can use them.
About dest option - you should specify relative path to output folder. For example 
`'./src/app/i18n'`
The same path should be in gulp.dest
`.pipe(gulp.dest('./src/app/i18n'));`
See example in readme file.

**Comment by elincognito** [comment]
Ok it seem to be working now, thanks.

Shouldn't dest be relative to `.pipe(gulp.dest('./src/app/i18n'));` ? It makes more sense

**Comment by ksenmal** [comment]
it shouldn't. 
you have destination and you should specify it to plugin in the same form.

**Comment by britvik** [comment]
What about safeMode? I set it to true and my old translations still get deleted. Am I missing something?

``` javascript
gulp.task('translate-extract', function() {
    gutil.log('Extracting on path: ' + options.src);
    return gulp.src(options.src)
        .pipe(translateExtract({
            defaultLang: 'en',
            lang: ['en', 'sk'],
            suffix: '.json',
            dest: config.translations.extractPath,
            safeMode: true,
            stringifyOptions: true
        }))
        .pipe(gulp.dest(config.translations.extractPath));
});
```

**Comment by ksenmal** [comment]
When I set `safeMode: true`, old translations are not actually deleted from output files.
Statistics says that something is deleted, but old translations are still there.

**Comment by britvik** [comment]
I checked it again and old translations were indeed not deleted. But I swear they got deleted before! :D Or maybe I just got confused by statistics output (which is btw quite misleading). Sorry for false alarm.
